name: Release

on:
  push:
    # 仅对以 v 开头的 tag 触发
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码（含 tags）
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装最新的 Python 3.x
      - name: Set up Python (latest 3.x)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # 3. 安装打包工具
      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      # 4. 生成分发包到 dist/
      - name: Build package
        run: python -m build

      # 5. 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # 6. 上传源码包 (.tar.gz)
      - name: Upload source archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.tar.gz
          asset_name: ${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      # 7. 上传 wheel 包 (.whl)
      - name: Upload wheel
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.whl
          asset_name: ${{ github.ref_name }}.whl
          asset_content_type: application/octet-stream

