name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (latest 3.x)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build
          ls -la dist/

      - name: Capture artifact paths
        id: capture
        run: |
          echo "TAR_PATH=$(ls dist/*.tar.gz)" >> $GITHUB_ENV
          echo "WHL_PATH=$(ls dist/*.whl)"    >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload source archive
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TAR_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload wheel
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.WHL_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
